### ISSUE TITLE
file:// cannot be used on Android >= 7

### ISSUE THREAD

**Issue by anolivetree** [karino2/MeatPieDay#3]
file:// URI cannot be used when you share a content bacause of a file system permission changes.
https://developer.android.com/about/versions/nougat/android-7.0-changes.html#permfilesys

10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err: io.reactivex.exceptions.UndeliverableException: android.os.FileUriExposedException: file:///storage/emulated/0/MeatPieDay/share_tmp/(New%20Book).ipynb exposed beyond app through ClipData.Item.getUri()
10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:64)
10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.os.Looper.loop(Looper.java:164)
10-15 23:33:42.224 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err: Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/MeatPieDay/share_tmp/(New%20Book).ipynb exposed beyond app through ClipData.Item.getUri()
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.net.Uri.checkFileUriExposed(Uri.java:2348)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
10-15 23:33:42.225 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4472)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4430)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.app.Activity.startActivity(Activity.java:4791)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at android.app.Activity.startActivity(Activity.java:4759)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at karino2.livejournal.com.meatpieday.BookSender.sendToFile(BookSender.java:48)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at karino2.livejournal.com.meatpieday.BookSender.lambda$sendTo$1(BookSender.java:57)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at karino2.livejournal.com.meatpieday.BookSender$$Lambda$4.accept(Unknown Source:4)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:61)
10-15 23:33:42.226 15921-15921/karino2.livejournal.com.meatpieday W/System.err: 	... 9 more

**Comment by karino2** [comment]
Fixed.
